# Generated by Django 5.1.1 on 2024-10-03 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protectora_animales', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colaborador',
            old_name='Cargo',
            new_name='cargo',
        ),
        migrations.RenameField(
            model_name='colaborador',
            old_name='Fecha_entrada_protectora',
            new_name='fecha_entrada_protectora',
        ),
    ]
